### PR TITLE
Created read me 

### PR DESCRIPTION
**Pull request by Varda003**
All the info about project is added
#22

### CODE REVIEW

**Comment by Varda003** [comment]
please @Akshatchaube01  merge this pull request.

**Comment by Akshatchaube01** [comment]
Add git commands in How to Contribute section

**Comment by Varda003** [comment]
No that was already added in the installation part containing a video tutorial as well

**Comment by Akshatchaube01** [comment]
We need git commands under the How to Contribute section.

**Comment by Varda003** [comment]
Okay adding that as well and making the desktop one as alternative. Is that fine??

**Comment by Varda003** [comment]
Check @Akshatchaube01  made all the changes added git commands as well please merge the pull request

**Comment by Varda003** [comment]
Hello @Akshatchaube01  Sir it would be great if you could provide me some review it was my first time contributing in open source how was the work any feedback will help

**Comment by Varda003** [comment]
hi @Akshatchaube01 my contribution was not counted in leaderboard it would be great if you could help as you add it in level 2 as well and merged it as different issue that's why may be it was not counted

**Comment by Varda003** [comment]
As I see no labels are assigned as well. Please I put a lot of effort in creating complete read me file

**Comment by Varda003** [comment]
sir my pr is not counted please add labels like "ggsoc" and "level2". please please

**Pull request merged**
