### PR TITLE
Fixed Contact Us Page Responding to Theme Change

### PR DESCRIPTION
**Pull request by say-het**
Hey! @Akshatchaube01
Firstly, thanks for assigning me this issue.

I have successfully fixed issue #186 
 - Now it changes text whenever the theme changes

Kindly review and merge it.
Thanks.

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
@say-het It still looks the same in light mode as it did before  
image

**Comment by say-het** [comment]
It is for contact us page not footer. The text on contact us page was the issue

**Comment by Akshatchaube01** [comment]
Oh okay my bad, got confused with another issue. Can you give the font on the contact us page some weight, they look very light right now.

**Comment by say-het** [comment]
Yeah Sure! @Akshatchaube01 Task Done. 
You can check & merge now.

**Pull request merged**
