### PR TITLE
Added issue template for documentation issues

### LINKED ISSUE #110: Add issues template for documentation issues
I would like to add a issues template for documentation issues in this repository. I believe that having a standardised template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review issues.

Could you please assign this issue to me under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #110

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
can you pull the recent changes and then commit

**Comment by suhanipaliwal** [comment]
Please merge this pull request.

**Comment by Akshatchaube01** [comment]
Please pull the recent changes, commit the changes and then tag me here. I will merge it

**Comment by suhanipaliwal** [comment]
> Please pull the recent changes, commit the changes and then tag me here. I will merge it

Done

**Pull request merged**
