### PR TITLE
Changed the cursor color and added dynamic background.

### PR DESCRIPTION
**Pull request by happyrao78**
@Akshatchaube01 #163 Solved.
Screenshot 2024-06-03 212000

Changed the color of cursor as earlier it was not visible in white background and also I have added the dynamic background to the aboutus, demosection and models section.
Preview:
Screenshot 2024-06-03 212031

Screenshot 2024-06-03 211946

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
Can you please pull the latest changes and commit

**Comment by happyrao78** [comment]
@Akshatchaube01 Pulled the changes and my branch is up to date with main branch.

**Comment by Akshatchaube01** [comment]
The changes made in the last PR are not visible in your work

**Comment by happyrao78** [comment]
@Akshatchaube01 But I have successfully raised the PR and also pulled recent all changes.

Screenshot 2024-06-03 235544

**Comment by Akshatchaube01** [comment]
There was a change just an hour ago, pull that too and then commit...

**Comment by happyrao78** [comment]
@Akshatchaube01 Kindly Check.

**Pull request merged**
