### PR TITLE
Added the feature of auto commenting when a PR is merged

### LINKED ISSUE #108: Auto Commenting when a PR is merged
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

### PR DESCRIPTION
**Pull request by suhanipaliwal**
Fixes #108

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
Please pull the recent changes so that I can merge the PR

**Comment by suhanipaliwal** [comment]
Please merge this pull request.

**Comment by Akshatchaube01** [comment]
Can you please pull the recent changes and commit, so that I can merge this PR

**Comment by suhanipaliwal** [comment]
> Can you please pull the recent changes and commit, so that I can merge this PR @suhanipaliwal

Done

**Pull request merged**
