### PR TITLE
Privacy policy

### LINKED ISSUE #235: [Feat] : We can create Privacy Page
**Is your feature request related to a problem? Please describe.**

@Akshatchaube01 
we can create privacy page for this web

**Describe the solution you'd like**
- we can design privacy policy for thiis website
- when user visit `/privacy-policy` they got access of this page

How do we know when the feature is complete?

### PR DESCRIPTION
**Pull request by dhruv8433**
# description:

[Feat] : We can create Privacy Page #235

close #235

## completed: 

- created privacy policy page
- make it as per website theme
- support dark and light mode
- make it responsible 
- design beautifully by adding some assets
- added hover effects

### light and dark mode

image

image

### responsive

image

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@Akshatchaube01 

kindly please check this and merge it
also if you need any modification then inform me

add lables as per issue #235

**Comment by Akshatchaube01** [comment]
@dhruv8433 Good work, can you remove the -  "information we collect" heading , and give space after every heading(similar to privacy policy) . I'll merge it after that !

**Comment by dhruv8433** [comment]
got it

**Comment by dhruv8433** [comment]
@Akshatchaube01 

as you say,
i removed "information we collect" and add some space after every heading

image

**Comment by Akshatchaube01** [comment]
Also, don't add policy page on the navigation bar, will do something else for it in other issues

**Comment by dhruv8433** [comment]
@Akshatchaube01 

Removed from navbar

**Comment by dhruv8433** [comment]
Thank you

**Pull request merged**
