### PR TITLE
Go To Top Button #136

### PR DESCRIPTION
**Pull request by prachita0504**
issue number : #136

### CODE REVIEW

**Comment by prachita0504** [comment]
@Akshatchaube01 please review this.

**Comment by Akshatchaube01** [comment]
Hey @prachita0504 , can you please pull the recent changes and then commit

**Comment by prachita0504** [comment]
can you tell me how to do that

**Comment by Akshatchaube01** [comment]
Git pull 
image

**Comment by prachita0504** [comment]
its already up to date

**Comment by Akshatchaube01** [comment]
Many changes have been made since your last commit, please check again

**Comment by prachita0504** [comment]
Screenshot 2024-06-02 124522

**Comment by prachita0504** [comment]
why you close this

**Pull request closed without merging**
