### PR TITLE
Made the changes in Cursor Trail effect

### PR DESCRIPTION
**Pull request by MastanSayyad**
@Akshatchaube01 I have made the changes, See if it is working fine in the preview 

https://github.com/Akshatchaube01/TimeWarp/assets/101971980/98b385fd-13f7-460e-8139-5120692982f4

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
It is not working

**Comment by MastanSayyad** [comment]
> It is not working

@Akshatchaube01 Let me try it once again

**Comment by MastanSayyad** [comment]
See if it is working now @Akshatchaube01

**Comment by Akshatchaube01** [comment]
Looks good !

**Pull request merged**
