### PR TITLE
worked on issue #101 -Linking our Team cards to Linkedin

### PR DESCRIPTION
**Pull request by raj-adi00**
Added hover effect using mouse enter and mouse leave effect on each card by targeting e.currentTarget. Icons are linked to google and github url. You can change them by updating details section and adding that particular attribute to that href. I have taken reference from the details provided by you in comment section of this issue.

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
Can you please pull the recent changes and then commit

**Comment by raj-adi00** [comment]
Hey @Akshatchaube01 i have pulled and then created pr now. It is my first open source contribution so i am not sure if i have done correctly or not

**Comment by raj-adi00** [comment]
or shall i create  a new PR???

**Comment by Akshatchaube01** [comment]
If you are facing issue in pulling the latest changes, then sure make a new PR

**Comment by raj-adi00** [comment]
Can you provide your discord ??

**Pull request closed without merging**
