### PR TITLE
Enhanced Navigation Bar-Final

### PR DESCRIPTION
**Pull request by yogirajbshinde21**
Fixes issue #337 

### **Description:**
This pull request enhances the navbar design to improve its aesthetics and user experience. 

- **The changes include several visual and interactive updates:**
Transparent Background: Updated the navbar and navbar list to have a transparent background with a subtle shadow for depth (rgba(0, 0, 0, 0.5)).

- **Link Element Enhancements: Enhanced link elements (<a>) with:**
1. White text color (#ffffff).
2. Text shadow (1px 1px 5px rgba(0, 0, 0, 0.5)).
3. Rounded corners (border-radius: 20px).
4. Smooth transitions for color, background, and transform properties (0.3s ease).
5. Hover Effects: Implemented dynamic hover effects on link elements:
6. Text color changes to light blue (#00bfff).
7. Background animation (rgba(255, 255, 255, 0.1)).
8. Scale transformation (transform: scale(1.05)).
9. Added a pseudo-element (::before) for a sliding background effect on hover.
10. Added a pseudo-element (::after) for a circle shrinking effect on hover.
11. Media Queries: Adjusted font sizes and spacings for responsiveness across different screen sizes (@media queries).
---
Updated Navigation Bar :

Screenshot 2024-06-26 144902

### CODE REVIEW

**Comment by yogirajbshinde21** [comment]
@Akshatchaube01 Could you please check this PR ?

**Comment by Akshatchaube01** [comment]
Cool, please be sure that you start working on an issue only after it has been assigned to you...I'll merge it this time

**Comment by yogirajbshinde21** [comment]
> Cool, please be sure that you start working on an issue only after it has been assigned to you...I'll merge it this time

Thank you very much! I'll definitely keep that in mind.

**Comment by yogirajbshinde21** [comment]
Hello @Akshatchaube01, after merging the pull request to the repository, I noticed that my contribution is not updated on the website's contributors list. Do I need to add it myself, or is there another process for updating it?

**Pull request merged**
