### PR TITLE
Added 3D Links

### PR DESCRIPTION
**Pull request by Mayur-666**
### Added 3d links to the website's landing page

Screenshot (523)

### CODE REVIEW

**Comment by Mayur-666** [comment]
@Akshatchaube01  The vercel bot is showing conflict at Home.jsx, cause i have removed vast code of Three js that was used to render the circles

**Comment by Stiffpixels** [comment]
did you pull cause some changes were made just a few minutes ago?

**Comment by Mayur-666** [comment]
@Stiffpixels  yes i pulled the latest copy, the conflict is just because the changes are too vast.

**Comment by Mayur-666** [comment]
@Akshatchaube01 Please resolve conflict and add changes that i pulled.

**Comment by Akshatchaube01** [comment]
The changes made by you are not visible in the preview

**Comment by Mayur-666** [comment]
@Akshatchaube01  Please add gssoc label and level tag in this PR otherwise it'll be little problematic for me.

**Pull request merged**
