### PR TITLE
Enhanced the design of model page image carousel

### PR DESCRIPTION
**Pull request by Stiffpixels**
As discussed in issue #33
- Fixed the buttons that are on the edges of screen
image

- made the model page more responsive for mobile and added titles to each carousel.
from this:
image
to this:
image

### CODE REVIEW

**Comment by Akshatchaube01** [comment]
Are you sure you pulled and pushed properly ? because the homepage background is still not up date with the main branch.

**Comment by Stiffpixels** [comment]
Now check @Akshatchaube01 I didnt pull the changes in my local repo which is why it was not updates.

**Comment by Akshatchaube01** [comment]
Looks good ! Thanks

**Comment by Stiffpixels** [comment]
can you assign a label to this PR @Akshatchaube01 and #31 so that points could be calculated for gssoc.

**Pull request merged**
